package com.example.Student_Library_Management_System.Services;


import com.example.Student_Library_Management_System.DTOs.StudentUpdateMobNoDTO;
import com.example.Student_Library_Management_System.Enum.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service

public class StudentService {

    @Autowired
    StudentRepository studentRepository;
    public String createStudent(Student student){

        // Student from the postman is already the basic attributes set.

        //Card should be autogenerated when createStudent function is called.

        Card card= new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student);


        //Lets go to the student
        student.setCard(card);

        //If there was a unidirectional mapping : we had to save both of them

        // Though  we are using bidirectional child will automatically gets saved

        studentRepository.save(student);
        return "Student and card added";
    }

    public String getNameByEmail(String email){
        Student student= studentRepository.findByEmail(email);
        return student.getName();
    }

    public String updateMobNo(StudentUpdateMobNoDTO student){
        Student originalStudent= studentRepository.findById(student.getId()).get();
        originalStudent.setMobNo(student.getMobNo());
        studentRepository.save(originalStudent);
        return "Updated successfully";
    }
}
